---
title: "modCathRes: Examples"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{examples}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(modelCathRes)
library(dplyr, quietly = T, warn.conflicts = F)
```

# Get test data

```{r plotCathodeResistance, include=TRUE}
data("resCathData")
d <- resCathData
head(d)
```


# Log model for cathode resistance


```{r lmModel, include=TRUE, fig.dim=c(8, 6)}
funLog <- modelCathRes::findLogFunction(d, agebsq, rucv)
# log fit curve
curve <-  ggplot2::stat_function(xlim = c(min(d$agebsq),
                                  max(d$agebsq)),
                         fun = funLog,
                         color = "darkred",
                         size = 1.2) 
ggplot2::ggplot(d, ggplot2::aes(x = agebsq, y = rucv)) +
  ggplot2::geom_point(shape = 21, fill = NA, size = .9, alpha = .5) +
  ggplot2::coord_cartesian(ylim = c(.4, 1.0)) +
  curve
```

# View cathode resistance and model for each pot

```{r plotCathRes, include=TRUE, fig.dim=c(8, 8)}
modelCathRes::plotCathRes(d, cod_cuve, agebsq, rucv, ncol = 4) +
  ggplot2::labs(title = "Evolution of Cathode Resistance per pot") +
  ggplot2::coord_cartesian(ylim = c(.5, 1.0)) +
  curve
```

# Comparing cathode resistance between 2 groups assuming same slope
Using lm with log function for age dependance

```{r compGroups, include=TRUE}
# Creating 2 groups in data d
d <- d %>% 
  mutate(group = ifelse(cod_cuve %in%  c("G148", "G110", "G096"), "GroupA", "GroupB"))
modelCathRes:::calculateResDiff(d, group, agebsq, rucv)
```

# Hierarchical model using lme4
## Intercept only

```{r lme4_1}
form <- as.formula(rucv ~ 1  + (1 | cod_cuve))
modLme1 <- lme4::lmer(formula = form,
                      data = d)
summary(modLme1)
# Intercept per pot
coef(modLme1)
# Intercept 
parameters::parameters(model = modLme1,
                       effects = "all")
```

```{r lme4_2}
form <- as.formula(rucv ~ 1 + log(agebsq) + ( 1 + log(agebsq) | cod_cuve))
modLme2 <- lme4::lmer(formula = form,
                      data = d)
summary(modLme2)
# Intercept per pot
coef(modLme2)
# Intercept global
parameters::model_parameters(model = modLme2, effects = "all", dig = 3)
```

